/* automatically generated by rust-bindgen 0.69.5 */

pub type int_least64_t = i64;
pub type uint_least64_t = u64;
pub type int_fast64_t = i64;
pub type uint_fast64_t = u64;
pub type int_least32_t = i32;
pub type uint_least32_t = u32;
pub type int_fast32_t = i32;
pub type uint_fast32_t = u32;
pub type int_least16_t = i16;
pub type uint_least16_t = u16;
pub type int_fast16_t = i16;
pub type uint_fast16_t = u16;
pub type int_least8_t = i8;
pub type uint_least8_t = u8;
pub type int_fast8_t = i8;
pub type uint_fast8_t = u8;
pub type intmax_t = ::core::ffi::c_longlong;
pub type uintmax_t = ::core::ffi::c_ulonglong;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct can2040_msg {
    pub id: u32,
    pub dlc: u32,
    pub __bindgen_anon_1: can2040_msg__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union can2040_msg__bindgen_ty_1 {
    pub data: [u8; 8usize],
    pub data32: [u32; 2usize],
}
pub const CAN2040_ID_RTR: _bindgen_ty_1 = 1073741824;
pub const CAN2040_ID_EFF: _bindgen_ty_1 = -2147483648;
pub type _bindgen_ty_1 = ::core::ffi::c_int;
pub const CAN2040_NOTIFY_RX: _bindgen_ty_2 = 1048576;
pub const CAN2040_NOTIFY_TX: _bindgen_ty_2 = 2097152;
pub const CAN2040_NOTIFY_ERROR: _bindgen_ty_2 = 8388608;
pub type _bindgen_ty_2 = ::core::ffi::c_uint;
pub type can2040_rx_cb = ::core::option::Option<
    unsafe extern "C" fn(cd: *mut can2040, notify: u32, msg: *mut can2040_msg),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct can2040_stats {
    pub rx_total: u32,
    pub tx_total: u32,
    pub tx_attempt: u32,
    pub parse_error: u32,
}
extern "C" {
    pub fn can2040_setup(cd: *mut can2040, pio_num: u32);
}
extern "C" {
    pub fn can2040_callback_config(cd: *mut can2040, rx_cb: can2040_rx_cb);
}
extern "C" {
    pub fn can2040_start(
        cd: *mut can2040,
        sys_clock: u32,
        bitrate: u32,
        gpio_rx: i32,
        gpio_tx: i32,
    );
}
extern "C" {
    pub fn can2040_stop(cd: *mut can2040);
}
extern "C" {
    pub fn can2040_get_statistics(cd: *mut can2040, stats: *mut can2040_stats);
}
extern "C" {
    pub fn can2040_pio_irq_handler(cd: *mut can2040);
}
extern "C" {
    pub fn can2040_check_transmit(cd: *mut can2040) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn can2040_transmit(cd: *mut can2040, msg: *mut can2040_msg) -> ::core::ffi::c_int;
}
#[doc = " Internal definitions"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct can2040_bitunstuffer {
    pub stuffed_bits: u32,
    pub count_stuff: u32,
    pub unstuffed_bits: u32,
    pub count_unstuff: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct can2040_transmit {
    pub msg: can2040_msg,
    pub crc: u32,
    pub stuffed_words: u32,
    pub stuffed_data: [u32; 5usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct can2040 {
    pub pio_num: u32,
    pub pio_hw: *mut ::core::ffi::c_void,
    pub gpio_rx: i32,
    pub gpio_tx: i32,
    pub rx_cb: can2040_rx_cb,
    pub stats: can2040_stats,
    pub unstuf: can2040_bitunstuffer,
    pub raw_bit_count: u32,
    pub parse_state: u32,
    pub parse_crc: u32,
    pub parse_crc_bits: u32,
    pub parse_crc_pos: u32,
    pub parse_msg: can2040_msg,
    pub report_state: u32,
    pub tx_state: u32,
    pub tx_pull_pos: u32,
    pub tx_push_pos: u32,
    pub tx_queue: [can2040_transmit; 4usize],
}
